import { ROLES } from "./roles";

export const PERMISSIONS = {
  CREATE_PROJECT: [ROLES.ADMIN],
  UPDATE_DELETE_PROJECT: [ROLES.ADMIN],
  MANAGE_MEMBERS: [ROLES.ADMIN],
  MANAGE_TASKS: [ROLES.ADMIN, ROLES.PROJECT_ADMIN],
  VIEW_TASKS: [ROLES.ADMIN, ROLES.PROJECT_ADMIN, ROLES.MEMBER],
  UPDATE_SUBTASK_STATUS: [ROLES.ADMIN, ROLES.PROJECT_ADMIN, ROLES.MEMBER],
  MANAGE_SUBTASKS: [ROLES.ADMIN, ROLES.PROJECT_ADMIN],
  MANAGE_NOTES: [ROLES.ADMIN],
  VIEW_NOTES: [ROLES.ADMIN, ROLES.PROJECT_ADMIN, ROLES.MEMBER],
};

export const hasPermission = (role, permissionKey) => {
  return PERMISSIONS[permissionKey]?.includes(role) ?? false;
};
